name: runTurbo
channels:
   - defaults
dependencies:
   # Core requirements
   - python=3.8
   - pip
   # Other packages
   - pandas
   - numpy
   # Allow Jupyter Kernel to be created
   - ipykernel
   # Install some other dependecies
   - pip:
     - git+https://github.com/UCBerkeleySETI/blimpy
     - git+https://github.com/UCBerkeleySETI/turbo_seti
     - pymysql
     - google-cloud-bigquery[bqstorage,pandas]